#!/bin/bash

echo "pid $$"
#echo "removing old results"
#rm -f *vec *gpd *sca simu*ini
GPDFILES="packeterrorrate.gpd packetbitrate.gpd controlframeerrorrate.gpd dataframeerrorrate.gpd packetnumfrag.gpd packetdelay.gpd dataframerate.gpd selectedmodes.gpd destnum.gpd timeoverheadrate.gpd bitoverheadrate.gpd"
for f in $GPDFILES
do
touch $f
done

for f in -9 -7 -5 -3 -1 1 3 5 7 9 11 ; 
do 
if [ ! -e simu_${f}.ini ] ;
then
echo "generating config for P_tx = $f"

cat omnetpp.ini params80211a.ini > simu_${f}.ini

echo **.transmissionPower=$f >> simu_${f}.ini

cat <<EOF >> simu_${f}.ini
[Run 1]
output-vector-file=simu_${f}_run0.vec
seed-N-mt = 2145055957
[Run 2]
output-vector-file=simu_${f}_run1.vec
seed-N-mt = 428022261
[Run 3]
output-vector-file=simu_${f}_run2.vec
seed-N-mt = 2036541398
[Run 4]
output-vector-file=simu_${f}_run3.vec
seed-N-mt = 1556910300
[Run 5]
output-vector-file=simu_${f}_run4.vec
seed-N-mt = 2050657052
[Run 6]
output-vector-file=simu_${f}_run5.vec
seed-N-mt = 1847406824
[Run 7]
output-vector-file=simu_${f}_run6.vec
seed-N-mt = 1047922642
[Run 8]
output-vector-file=simu_${f}_run7.vec
seed-N-mt = 922455047
[Run 9]
output-vector-file=simu_${f}_run8.vec
seed-N-mt = 1017527236
[Run 10]
output-vector-file=simu_${f}_run9.vec
seed-N-mt = 1167974391
EOF

echo "running simulation for P_tx = $f"

#echo "runs 1-5"
#./802.11a -f simu_${f}.ini -r 1-5 1> /tmp/simu${f}_1.log & 
#echo "runs 6-10"
#./802.11a -f simu_${f}.ini -r 5-10 1> /tmp/simu${f}_2.log 

./802.11a -f simu_${f}.ini -r 1 > /tmp/$$_$f.log
cat /tmp/$$_$f.log | grep GNUPLOT_PACKETERRORRATE | sed -e "s/GNUPLOT_PACKETERRORRATE/$f/g"
cat /tmp/$$_$f.log | grep GNUPLOT_PACKETERRORRATE | sed -e "s/GNUPLOT_PACKETERRORRATE/$f/g" >> packeterrorrate.gpd
cat /tmp/$$_$f.log | grep GNUPLOT_PACKETBITRATE | sed -e "s/GNUPLOT_PACKETBITRATE/$f/g"
cat /tmp/$$_$f.log | grep GNUPLOT_PACKETBITRATE | sed -e "s/GNUPLOT_PACKETBITRATE/$f/g" >> packetbitrate.gpd
cat /tmp/$$_$f.log | grep GNUPLOT_CONTROLFRAMEERRORRATE | sed -e "s/GNUPLOT_CONTROLFRAMEERRORRATE/$f/g"
cat /tmp/$$_$f.log | grep GNUPLOT_CONTROLFRAMEERRORRATE | sed -e "s/GNUPLOT_CONTROLFRAMEERRORRATE/$f/g" >> controlframeerrorrate.gpd
cat /tmp/$$_$f.log | grep GNUPLOT_DATAFRAMEERRORRATE | sed -e "s/GNUPLOT_DATAFRAMEERRORRATE/$f/g"
cat /tmp/$$_$f.log | grep GNUPLOT_DATAFRAMEERRORRATE | sed -e "s/GNUPLOT_DATAFRAMEERRORRATE/$f/g" >> dataframeerrorrate.gpd
cat /tmp/$$_$f.log | grep GNUPLOT_PACKETNUMFRAG | sed -e "s/GNUPLOT_PACKETNUMFRAG/$f/g"
cat /tmp/$$_$f.log | grep GNUPLOT_PACKETNUMFRAG | sed -e "s/GNUPLOT_PACKETNUMFRAG/$f/g" >> packetnumfrag.gpd
cat /tmp/$$_$f.log | grep GNUPLOT_PACKETDELAY | sed -e "s/GNUPLOT_PACKETDELAY/$f/g"
cat /tmp/$$_$f.log | grep GNUPLOT_PACKETDELAY | sed -e "s/GNUPLOT_PACKETDELAY/$f/g" >> packetdelay.gpd
cat /tmp/$$_$f.log | grep GNUPLOT_DATAFRAMERATE | sed -e "s/GNUPLOT_DATAFRAMERATE/$f/g"
cat /tmp/$$_$f.log | grep GNUPLOT_DATAFRAMERATE | sed -e "s/GNUPLOT_DATAFRAMERATE/$f/g" >> dataframerate.gpd
cat /tmp/$$_$f.log | grep GNUPLOT_SELECTEDMODES | sed -e "s/GNUPLOT_SELECTEDMODES/$f/g"
cat /tmp/$$_$f.log | grep GNUPLOT_SELECTEDMODES | sed -e "s/GNUPLOT_SELECTEDMODES/$f/g" >> selectedmodes.gpd
cat /tmp/$$_$f.log | grep GNUPLOT_DESTNUM | sed -e "s/GNUPLOT_DESTNUM/$f/g"
cat /tmp/$$_$f.log | grep GNUPLOT_DESTNUM | sed -e "s/GNUPLOT_DESTNUM/$f/g" >> destnum.gpd
cat /tmp/$$_$f.log | grep GNUPLOT_TIMEOVERHEAD_RATE | sed -e "s/GNUPLOT_TIMEOVERHEAD_RATE/$f/g"
cat /tmp/$$_$f.log | grep GNUPLOT_TIMEOVERHEAD_RATE | sed -e "s/GNUPLOT_TIMEOVERHEAD_RATE/$f/g" >> timeoverhead_rate.gpd
cat /tmp/$$_$f.log | grep GNUPLOT_BITOVERHEAD_RATE | sed -e "s/GNUPLOT_BITOVERHEAD_RATE/$f/g"
cat /tmp/$$_$f.log | grep GNUPLOT_BITOVERHEAD_RATE | sed -e "s/GNUPLOT_BITOVERHEAD_RATE/$f/g" >> bitoverhead_rate.gpd
#rm -f $$.log

fi

done
#for f in delay rate payload errorrate ;
#do 
#gnuplot $f.gnuplot > $f.fig 
#done
