//
// Generated file, do not edit! Created by opp_msgc 4.0 from messages/Mac80211Pkt.msg.
//

#ifndef _MAC80211PKT_M_H_
#define _MAC80211PKT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0400
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{ ... }} section:

#include "MacPkt_m.h"
// end cplusplus



/**
 * Class generated from <tt>messages/Mac80211Pkt.msg</tt> by opp_msgc.
 * <pre>
 * packet Mac80211Pkt extends MacPkt
 * {
 *     int address3;
 *     int address4;
 *     int fragmentation; 
 *     int informationDS; 
 *     int sequenceControl;
 *     bool retry;
 *     simtime_t duration; 	
 * 						
 * }
 * </pre>
 */
class Mac80211Pkt : public MacPkt
{
  protected:
    int address3_var;
    int address4_var;
    int fragmentation_var;
    int informationDS_var;
    int sequenceControl_var;
    bool retry_var;
    simtime_t duration_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Mac80211Pkt&);

  public:
    Mac80211Pkt(const char *name=NULL, int kind=0);
    Mac80211Pkt(const Mac80211Pkt& other);
    virtual ~Mac80211Pkt();
    Mac80211Pkt& operator=(const Mac80211Pkt& other);
    virtual Mac80211Pkt *dup() const {return new Mac80211Pkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getAddress3() const;
    virtual void setAddress3(int address3_var);
    virtual int getAddress4() const;
    virtual void setAddress4(int address4_var);
    virtual int getFragmentation() const;
    virtual void setFragmentation(int fragmentation_var);
    virtual int getInformationDS() const;
    virtual void setInformationDS(int informationDS_var);
    virtual int getSequenceControl() const;
    virtual void setSequenceControl(int sequenceControl_var);
    virtual bool getRetry() const;
    virtual void setRetry(bool retry_var);
    virtual simtime_t getDuration() const;
    virtual void setDuration(simtime_t duration_var);
};

inline void doPacking(cCommBuffer *b, Mac80211Pkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Mac80211Pkt& obj) {obj.parsimUnpack(b);}


#endif // _MAC80211PKT_M_H_
