#!/bin/bash

#
# Copyright (C) 2020 Christoph Sommer <sommer@cms-labs.org>
#
# Documentation for these modules is at http://veins.car2x.org/
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

echo "WARNING: the run script is deprecated in favor of bin/veins_testsims_run. Redirecting." >&2
echo "WARNING: the run script is deprecated in favor of bin/veins_testsims_run. Redirecting."

test -f $(dirname "$0")/bin/veins_testsims_run || echo "ERROR: bin/veins_testsims_run does not exist; this will likely fail. Did you run 'make bin/veins_testsims_run'?" >&2
test -f $(dirname "$0")/bin/veins_testsims_run || echo "ERROR: bin/veins_testsims_run does not exist; this will likely fail. Did you run 'make bin/veins_testsims_run'?"

$(dirname "$0")/bin/veins_testsims_run "$@"

echo "WARNING: the run script is deprecated in favor of bin/veins_testsims_run. Redirection done." >&2
echo "WARNING: the run script is deprecated in favor of bin/veins_testsims_run. Redirection done."

