#!/bin/bash
# 
# script to recreate all makefiles for linux

# set root directory
ROOT=`pwd`

if [ ! -f omnetppconfig ]; then
	# make omnetppconfig if it doesn't exist
	opp_makemake -f --genconfig omnetppconfig
fi	

# copy lib makefrag for linux
(cd $ROOT/lib && cp makefrag.linux makefrag)

make ROOT=$ROOT -f Makefile.linux

exit 0
