#!/bin/bash
# 
# script to recreate all makefiles for linux

# set root directory
ROOT=`pwd`

# make omnetppconfig
opp_makemake -f --genconfig omnetppconfig

make ROOT=$ROOT -f Makefile.linux

exit 0
