.\"                              hey, Emacs:   -*- nroff -*-
.\" mixim_generator is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH MIXIM_GENERATOR 1 "January 26, 2006"
.\" Please update the above date whenever this man page is modified.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins (default)
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
mixim_generator \- Generates config files for use with MiXiM
.SH SYNOPSIS
.B mixim_generator
.RI [ options ]
.SH DESCRIPTION
\fBmixim_generator\fP washes your windows, mends your fences, mows your lawn...
.PP
It also...
.SH OPTIONS
\fBmixim_generator\fP accepts the following options:
.TP
.BR  -q ", " --quiet ", " --silent
Inhibit usual output.
.TP
.BR  -v ", " --verbose
Print more information.
.TP
.BI  --directory= name
Use specified directory.
.TP
.BR  -? ", " --help
List all available options and their meanings.
.TP
.B  --usage
Show summary of options.
.TP
.BR  -V ", " --version
Show version of program.
.\" .SH "SEE ALSO"
.\" .BR foo (1), 
.\" .BR bar (1).
.SH AUTHOR
Otto Visser <o.w.visser@tudelft.nl>.
