#!/bin/sh
for i in {0..549};
do 
    akrun -n 8 -c 0.95 -e 0.01 -a 0.0001 -- ./run -f akaroa.ini -u Cmdenv -c BERDistance -r $i > ./akresults/ak-berdistance-$i.out 2> ./akresults/ak-berdistance-$i.err ; 
done


