#!/bin/sh
for i in {0..49};
do 
    akrun -n 2 -c 0.99 -e 0.02 -- ./run -f akaroa.ini -u Cmdenv -c MAICircleN -r $i > ./akresults/ak-maiunif-$i.out 2> ./akresults/ak-maiunif-$i.err ; 
    killall opp_run ;
done


