#!/bin/bash

CFG=epflEbN0
NBPARALLEL=6
CFGFILE=noakaroa.ini

CREATION_INTERVAL=1
NBRUNS=$((`./run -f $CFGFILE -x $CFG |  grep -o [[:space:]][[:digit:]]*$ `))

echo Ready to start $NBPARALLEL simultaneous opp_run processes until $NBRUNS are done...

RUN=0
while [[ $RUN -lt $NBRUNS && `ls results/$CFG-*.sca | wc -l` -lt $NBRUNS ]] ; do
   NBOPPRUNS=$(ps -eo args | grep run_mf | grep -o \\-r[[:space:]][[:digit:]]* | awk '{ print $2}' | wc -l)
  if [[ $NBOPPRUNS -lt $NBPARALLEL && $RUN -lt $NBRUNS ]] ; then
    nice -n 15 ./run -f $CFGFILE -u Cmdenv -c $CFG -r $RUN &
    RUN=$(($RUN+1))
  fi
  sleep $CREATION_INTERVAL   # avoid going too fast
done

