MAKEMAKE=opp_makemake 

OPTS=-f -b $(ROOT) -c $(ROOT)/omnetppconfig
LIB_OPTS=-w -o libmfcore -s 

CORE_LIB=-L$(ROOT)/core/lib -lmfcore 
CONTRIB_LIB=-L$(ROOT)/contrib/lib -lmfcontrib 

include makemakefiles
