CC=cl.exe /nologo
LINK=link.exe /nologo

TARGET=mixim_generator.exe

all: $(TARGET)

OBJS=mixim_generator.obj

$(TARGET): $(OBJS) $(EXTRA_OBJS) $(EXT_DIR_TSTAMPS)  Makefile.vc
	$(LINK) $(LDFLAGS) $(OBJS) $(EXTRA_OBJS) $(EXT_DIR_OBJS) $(LIBS) $(OMNETPP_LIBS) /out:$(TARGET)

mixim_generator.obj: mixim_generator.c
	$(CC) -c /Tp mixim_generator.c

