all: aclocal.m4 config.h.in Makefile.in configure

aclocal.m4:
	aclocal

config.h.in:
	autoheader

Makefile.in: Makefile.am configure
	automake -a

configure: configure.in
	autoconf

clean:
	@rm -f aclocal.m4 config.h.in Makefile.in configure

